### PR TITLE
Update routes

### LINKED ISSUE #28: "No route found for path"
After installing this plugin, I get the following error when trying to access the create dialog:

Bildschirmfoto am 2020-09-23 um 11 00 38

```json
{
    "code": 404,
    "details": [],
    "exception": "Exception",
    "file": "/example/kirby/src/Http/Router.php",
    "key": null,
    "line": 154,
    "message": "No route found for path: \"pages/example/blueprints/add-fields\" and request method: \"GET\"",
    "route": null,
    "status": "error"
}
```

It doesn't matter if there are custom add fields or not.
We are using Kirby 3.4.3.

### PR DESCRIPTION
**Pull request by nilshoerrmann**
This pull request ensure the plugins listens to the new default routes used by Kirby.

Fixes #28

### CODE REVIEW

**Comment by steirico** [comment]
Thanks for your contribution.

This PR will makes future versions of the plugin incompatible with kirby prior to v3.4.3.

I would prefer a fix that is backward compatible.

**Comment by nilshoerrmann** [comment]
Right, didn't think about that. What about:

```php       
                'pattern' => [
                    'site/children/blueprints/add-fields',
                    'site/blueprints/add-fields',
                    'pages/(:any)/children/blueprints/add-fields',
                    'pages/(:any)/blueprints/add-fields',
                ]
```

**Comment by steirico** [comment]
LGTM!

**Comment by nilshoerrmann** [comment]
Great, I just updated the routes.

**Review by steirico — APPROVED** [review]

**Pull request merged**
